-- Create table to hold last row of file
CREATE TABLE dbo.Dummy_Data_BCP_Trailer (
	FILENAME VARCHAR(50),
	RECORDIDENTIFIER CHAR(1),
	TOTALNUMBEROFCLAIMS CHAR(9),
	TOTALAMOUNTPAYABLE CHAR(14),
	TOTALADMINFEEAMOUNT CHAR(9),
	FILLER CHAR(917)
)
;
GO