--Create table to hold header record of file
CREATE TABLE dbo.Dummy_Data_BCP_Header (
	FILENAME VARCHAR(50),
	RECORDIDENTIFIER CHAR(1),
	RUNDATE CHAR(8),
	SENDINGCOMPANYNAME CHAR(20),
	CYCLESTARTDATE CHAR(8),
	CYCLEENDDATE CHAR(8),
	FILLER CHAR(905)
)
;
GO