USE HealthStrategy;
GO
-- Import MediSpan lookup tables

-- Create schema to separate raw data from cleaned up and transformed data
CREATE SCHEMA RawSource;
GO
-- Create table to hold raw data
CREATE TABLE RawSource.DummyData_Brooke_File1_BCP (
	LineFromFile VARCHAR(max)
	, LineNumber INT IDENTITY(1,1) NOT NULL
)
;
GO
CREATE TABLE RawSource.DummyData_Brooke_File2_BCP (
	LineFromFile VARCHAR(max)
	, LineNumber INT IDENTITY(1,1) NOT NULL
)
;
GO













/*
Already created BCP format file with the following command:

bcp HealthStrategy.RawSource.DummyData_Brooke_File1_BCP format nul -c -x -f "C:\Users\Brooke\BCPFormatFile.xml" -t, -T -S DESKTOP-G4V2OAO\SQLEXPRESS
*/


--bcp HealthStrategy.RawSource.DummyData_Brooke_File1_BCP IN "C:\Users\Brooke\Desktop\Skills_Evaluation\DummyData_Brooke_File1.txt" -f "C:\GITProjects\HS-BCP-Solution\BCPFormatFile.xml" -T -S DESKTOP-G4V2OAO\SQLEXPRESS
--bcp HealthStrategy.RawSource.DummyData_Brooke_File2_BCP IN "C:\Users\Brooke\Desktop\Skills_Evaluation\DummyData_Brooke_File2.txt" -f "C:\GITProjects\HS-BCP-Solution\BCPFormatFile.xml" -T -S DESKTOP-G4V2OAO\SQLEXPRESS













































--Create table to hold header record of file
CREATE TABLE dbo.Dummy_Data_BCP_Header (
	FILENAME VARCHAR(50),
	RECORDIDENTIFIER CHAR(1),
	RUNDATE CHAR(8),
	SENDINGCOMPANYNAME CHAR(20),
	CYCLESTARTDATE CHAR(8),
	CYCLEENDDATE CHAR(8),
	FILLER CHAR(905)
)
;
GO






















--Create table of data fields to import into
CREATE TABLE dbo.Dummy_Data_BCP_00_Native (
	RECORDIDENTIFIER CHAR(1),
	CARRIERID CHAR(20),
	ACCOUNTIDGROUPEXTENSIONCODE CHAR(15),
	GROUPID CHAR(15),
	CARDHOLDERMEMBERID CHAR(20),
	ALTERNATEID CHAR(20),
	CAREFACILITYID CHAR(10),
	PERSONCODE CHAR(3),
	CARDHOLDERLASTNAME CHAR(25),
	CARDHOLDERFIRSTNAME CHAR(25),
	CARDHOLDERMIDDLEINITIAL CHAR(1),
	PATIENTLASTNAME CHAR(25),
	PATIENTFIRSTNAME CHAR(15),
	PATIENTBIRTHDATE CHAR(8),
	PATIENTSEX CHAR(1),
	RELATIONSHIPCODE CHAR(1),
	FILLER CHAR(10),
	PROVIDERID  CHAR(15),
	PROVIDERIDQUALIFIER CHAR(2),
	PROVIDERNAME CHAR(20),
	NETWORKID CHAR(6),
	RXNUMBER CHAR(9),
	RXNUMBERQUALIFIER CHAR(1),
	DATEFILLED CHAR(8),
	DATEPRESCRIPTIONWRITTEN CHAR(8),
	RXCLAIMDATEPROCESSED CHAR(8),
	TRANSACTIONID CHAR(18),
	CLAIMSTATUSFLAG CHAR(1),
	CLAIMORIGINATIONFLAG CHAR(1),
	REIMBURSEMENTTYPE CHAR(1),
	NEWREFILLNUMBER CHAR(2),
	NUMBEROFREFILLSAUTHORIZED CHAR(2),
	PRICESOURCEINDICATOR CHAR(10),
	PRODUCTID CHAR(20),
	PRODUCTIDQUALIFIER CHAR(2),
	DRUGNAME CHAR(30),
	DRUGADMINISTRATIONROUTECODE CHAR(2),
	GPICODE CHAR(14),
	MEDBMEDDINDICATOR CHAR(1),
	FILLER2 CHAR(4),
	GENERICCLASS CHAR(5),
	GENERICNAME CHAR(60),
	GENERICBRANDINDICATOR CHAR(1),
	THERAPEUTICCLASSAHFSCODE CHAR(6),
	MULTISINGLESOURCEINDICATOR CHAR(1),
	DRUGDOSAGEFORM CHAR(4),
	DRUGSTRENGTH CHAR(10),
	DEACLASS CHAR(2),
	COMPOUNDINDICATOR CHAR(1),
	PRODUCTSELECTIONCODEDAW CHAR(1),
	OTHERCOVERAGE CHAR(1),
	PAYABLEQUANTITY CHAR(11),
	PHARMACYAMOUNTSUBMITTEDUC CHAR(9),
	DAYSSUPPLY CHAR(3),
	SUBMITTEDINGREDIENTCOST CHAR(9),
	INGREDIENTCOSTPAYABLE CHAR(9),
	SUBMITTEDDISPENSINGFEE CHAR(9),
	DISPENSINGFEEPAYABLE CHAR(9),
	SUBMITTEDSALESTAX CHAR(9),
	SALESTAXPAYABLE CHAR(9),
	SUBMITTEDGROSSAMOUNTDUE CHAR(9),
	AMOUNTBILLED CHAR(9),
	SUBMITTEDPATIENTPAYAMOUNT CHAR(9),
	PATIENTPAYAMOUNT CHAR(9),
	FLATCOPAYAMOUNTPAID CHAR(9),
	PERCENTCOPAYAMOUNTPAID CHAR(9),
	ADMINFEE CHAR(5),
	MAINTENANCEDRUGINDICATOR CHAR(1),
	FINALPLANCODE CHAR(10),
	PLANCODEEXTENSION CHAR(8),
	FILLER3 CHAR(1),
	CARDHOLDERCOPAYDIFFERENTIAL CHAR(9),
	FRONTENDDEDUCTIBLEAMOUNT CHAR(9),
	AFTERMAXAMOUNT CHAR(9),
	TOTALCOPAYAMOUNT CHAR(9),
	PATIENTACCUMULATEDDEDUCTIBLEAMOUNT CHAR(9),
	DISPENSERTYPE CHAR(3),
	AWP CHAR(10),
	AWPTYPEINDICATOR CHAR(1),
	BILLINGREPORTINGCODE CHAR(3),
	FORMULARYINDICATORFORMULARYSTATUS CHAR(1),
	REJECTCODE1 CHAR(3),
	PRIORAUTHORIZATIONNUMBER CHAR(11),
	PRIORAUTHORIZATIONREASONCODES CHAR(2),
	PAMCSCCODEANDNUMBER CHAR(12),
	BASISOFCOSTDETERMINATION CHAR(2),
	PRESCRIBERNUMBER CHAR(15),
	PRESCRIBERIDQUALIFER CHAR(2),
	PERFORMANCERXPHARMACYFEEPAID CHAR(5),
	PERFORMANCERXFEEPAID CHAR(5),
	D0RXNUMBER CHAR(15),
	RXNUMBERQUALIFIER2 CHAR(1),
	ADJUSTMENTREASONCODE CHAR(3),
	ADJUSTMENTISSUEID CHAR(10),
	REBILLINCENTIVE CHAR(9),
	VACCINECLAIMINDICATOR CHAR(1),
	CARENETWORK CHAR(10),
	CAREQUALIFIER CHAR(10),
	COBPRIMARYPAYERAMOUNTPAID CHAR(8),
	APPLIEDHRAAMOUNT CHAR(11),
	BILLINGCYCLEENDDATE CHAR(8),
	MAINTENANCECHOICEINDICATOR CHAR(1),
	OPARAMOUNT CHAR(8),
	CB5QUALIFIER CHAR(2),
	CB5OTHAMOUNT1 CHAR(9),
	CB5QUALIFIER2 CHAR(2),
	CB5OTHAMOUNT2 CHAR(9),
	CB5QUALIFIER3 CHAR(2),
	CB5OTHAMOUNT3 CHAR(9),
	PD6CLIENTTOTALOTHERAMOUNT CHAR(9),
	PD6BUYTOTALOTHERAMOUNT CHAR(9),
	DIAGNOSISCODEQUALIFIER CHAR(2),
	DIAGNOSISCODE CHAR(15),
	FILLER4 CHAR(19)
)
;
GO

CREATE TABLE dbo.Dummy_Data_BCP_01_Native (
	RECORDIDENTIFIER CHAR(1),
	CARRIERID CHAR(20),
	ACCOUNTIDGROUPEXTENSIONCODE CHAR(15),
	GROUPID CHAR(15),
	CARDHOLDERMEMBERID CHAR(20),
	ALTERNATEID CHAR(20),
	CAREFACILITYID CHAR(10),
	PERSONCODE CHAR(3),
	CARDHOLDERLASTNAME CHAR(25),
	CARDHOLDERFIRSTNAME CHAR(25),
	CARDHOLDERMIDDLEINITIAL CHAR(1),
	PATIENTLASTNAME CHAR(25),
	PATIENTFIRSTNAME CHAR(15),
	PATIENTBIRTHDATE CHAR(8),
	PATIENTSEX CHAR(1),
	RELATIONSHIPCODE CHAR(1),
	FILLER CHAR(10),
	PROVIDERID  CHAR(15),
	PROVIDERIDQUALIFIER CHAR(2),
	PROVIDERNAME CHAR(20),
	NETWORKID CHAR(6),
	RXNUMBER CHAR(9),
	RXNUMBERQUALIFIER CHAR(1),
	DATEFILLED CHAR(8),
	DATEPRESCRIPTIONWRITTEN CHAR(8),
	RXCLAIMDATEPROCESSED CHAR(8),
	TRANSACTIONID CHAR(18),
	CLAIMSTATUSFLAG CHAR(1),
	CLAIMORIGINATIONFLAG CHAR(1),
	REIMBURSEMENTTYPE CHAR(1),
	NEWREFILLNUMBER CHAR(2),
	NUMBEROFREFILLSAUTHORIZED CHAR(2),
	PRICESOURCEINDICATOR CHAR(10),
	PRODUCTID CHAR(20),
	PRODUCTIDQUALIFIER CHAR(2),
	DRUGNAME CHAR(30),
	DRUGADMINISTRATIONROUTECODE CHAR(2),
	GPICODE CHAR(14),
	MEDBMEDDINDICATOR CHAR(1),
	FILLER2 CHAR(4),
	GENERICCLASS CHAR(5),
	GENERICNAME CHAR(60),
	GENERICBRANDINDICATOR CHAR(1),
	THERAPEUTICCLASSAHFSCODE CHAR(6),
	MULTISINGLESOURCEINDICATOR CHAR(1),
	DRUGDOSAGEFORM CHAR(4),
	DRUGSTRENGTH CHAR(10),
	DEACLASS CHAR(2),
	COMPOUNDINDICATOR CHAR(1),
	PRODUCTSELECTIONCODEDAW CHAR(1),
	OTHERCOVERAGE CHAR(1),
	PAYABLEQUANTITY CHAR(11),
	PHARMACYAMOUNTSUBMITTEDUC CHAR(9),
	DAYSSUPPLY CHAR(3),
	SUBMITTEDINGREDIENTCOST CHAR(9),
	INGREDIENTCOSTPAYABLE CHAR(9),
	SUBMITTEDDISPENSINGFEE CHAR(9),
	DISPENSINGFEEPAYABLE CHAR(9),
	SUBMITTEDSALESTAX CHAR(9),
	SALESTAXPAYABLE CHAR(9),
	SUBMITTEDGROSSAMOUNTDUE CHAR(9),
	AMOUNTBILLED CHAR(9),
	SUBMITTEDPATIENTPAYAMOUNT CHAR(9),
	PATIENTPAYAMOUNT CHAR(9),
	FLATCOPAYAMOUNTPAID CHAR(9),
	PERCENTCOPAYAMOUNTPAID CHAR(9),
	ADMINFEE CHAR(5),
	MAINTENANCEDRUGINDICATOR CHAR(1),
	FINALPLANCODE CHAR(10),
	PLANCODEEXTENSION CHAR(8),
	FILLER3 CHAR(1),
	CARDHOLDERCOPAYDIFFERENTIAL CHAR(9),
	FRONTENDDEDUCTIBLEAMOUNT CHAR(9),
	AFTERMAXAMOUNT CHAR(9),
	TOTALCOPAYAMOUNT CHAR(9),
	PATIENTACCUMULATEDDEDUCTIBLEAMOUNT CHAR(9),
	DISPENSERTYPE CHAR(3),
	AWP CHAR(10),
	AWPTYPEINDICATOR CHAR(1),
	BILLINGREPORTINGCODE CHAR(3),
	FORMULARYINDICATORFORMULARYSTATUS CHAR(1),
	REJECTCODE1 CHAR(3),
	PRIORAUTHORIZATIONNUMBER CHAR(11),
	PRIORAUTHORIZATIONREASONCODES CHAR(2),
	PAMCSCCODEANDNUMBER CHAR(12),
	BASISOFCOSTDETERMINATION CHAR(2),
	PRESCRIBERNUMBER CHAR(15),
	PRESCRIBERIDQUALIFER CHAR(2),
	PERFORMANCERXPHARMACYFEEPAID CHAR(5),
	PERFORMANCERXFEEPAID CHAR(5),
	D0RXNUMBER CHAR(15),
	RXNUMBERQUALIFIER2 CHAR(1),
	ADJUSTMENTREASONCODE CHAR(3),
	ADJUSTMENTISSUEID CHAR(10),
	REBILLINCENTIVE CHAR(9),
	VACCINECLAIMINDICATOR CHAR(1),
	CARENETWORK CHAR(10),
	CAREQUALIFIER CHAR(10),
	COBPRIMARYPAYERAMOUNTPAID CHAR(8),
	APPLIEDHRAAMOUNT CHAR(11),
	BILLINGCYCLEENDDATE CHAR(8),
	MAINTENANCECHOICEINDICATOR CHAR(1),
	OPARAMOUNT CHAR(8),
	CB5QUALIFIER CHAR(2),
	CB5OTHAMOUNT1 CHAR(9),
	CB5QUALIFIER2 CHAR(2),
	CB5OTHAMOUNT2 CHAR(9),
	CB5QUALIFIER3 CHAR(2),
	CB5OTHAMOUNT3 CHAR(9),
	PD6CLIENTTOTALOTHERAMOUNT CHAR(9),
	PD6BUYTOTALOTHERAMOUNT CHAR(9),
	DIAGNOSISCODEQUALIFIER CHAR(2),
	DIAGNOSISCODE CHAR(15),
	FILLER4 CHAR(19)
)
;
GO


























-- Create table to hold last row of file
CREATE TABLE dbo.Dummy_Data_BCP_Trailer (
	FILENAME VARCHAR(50),
	RECORDIDENTIFIER CHAR(1),
	TOTALNUMBEROFCLAIMS CHAR(9),
	TOTALAMOUNTPAYABLE CHAR(14),
	TOTALADMINFEEAMOUNT CHAR(9),
	FILLER CHAR(917)
)
;
GO



























USE HealthStrategy
GO
CREATE PROC dbo.ParseDataFile1
AS
BEGIN
	DECLARE @Filename VARCHAR(50) = 'DummyData_Brooke_File1.txt';
	DECLARE @NumberOfLines INT;
	DECLARE @sqlQuery NVARCHAR(4000);
	DECLARE @ParmDefinition NVARCHAR(500);

	SELECT @NumberOfLines = MAX(RS.LineNumber) 
	FROM RawSource.DummyData_Brooke_File1_BCP RS
	;

	-- Put header into table
	INSERT INTO dbo.Dummy_Data_BCP_Header(
		FILENAME,
		RECORDIDENTIFIER,
		RUNDATE,
		SENDINGCOMPANYNAME,
		CYCLESTARTDATE,
		CYCLEENDDATE,
		FILLER
	)
	SELECT
	@Filename as Filename
	, LEFT(RS.LineFromFile, 1) as RecordIdentifier
	, RIGHT(LEFT(RS.LineFromFile, 9), 8) as RunDate
	, RIGHT(LEFT(RS.LineFromFile, 29), 20) as SendingCompanyName
	, RIGHT(LEFT(RS.LineFromFile, 37), 8) as CycleStartDate
	, RIGHT(LEFT(RS.LineFromFile, 45), 8) as CycleEndDate
	, RIGHT(RS.LineFromFile, 905) as Filler
	FROM RawSource.DummyData_Brooke_File1_BCP RS
	WHERE RS.LineNumber = 1
	;
	
	--Put trailer into table
	INSERT INTO dbo.Dummy_Data_BCP_Trailer(
		FILENAME,
		RECORDIDENTIFIER,
		TOTALNUMBEROFCLAIMS,
		TOTALAMOUNTPAYABLE,
		TOTALADMINFEEAMOUNT,
		FILLER
	)
	SELECT
	@Filename as Filename
	, LEFT(RS.LineFromFile, 1) as RecordIdentifier
	, RIGHT(LEFT(RS.LineFromFile, 10), 9) as TotalNumberOfClaims
	, RIGHT(LEFT(RS.LineFromFile, 24), 14) as TotalAmountPayable
	, RIGHT(LEFT(RS.LineFromFile, 33), 9) as TotalAdminFeeAmount
	, RIGHT(RS.LineFromFile, 917) as Filler
	FROM RawSource.DummyData_Brooke_File1_BCP RS
	WHERE RS.LineNumber = @NumberOfLines
	;

	-- PARSE DATA LINES INTO DESTINATION TABLE
	INSERT INTO dbo.Dummy_Data_BCP_00_Native
	SELECT
		LEFT(RS.LineFromFile, 1) as RecordIdentifier
		, RIGHT(LEFT(RS.LineFromFile,21),20) as CARRIERID
		, RIGHT(LEFT(RS.LineFromFile,36),15) as ACCOUNTIDGROUPEXTENSIONCODE
		, RIGHT(LEFT(RS.LineFromFile,51),15) as GROUPID
		, RIGHT(LEFT(RS.LineFromFile,71),20) as CARDHOLDERMEMBERID
		, RIGHT(LEFT(RS.LineFromFile,91),20) as ALTERNATEID
		, RIGHT(LEFT(RS.LineFromFile,101),10) as CAREFACILITYID
		, RIGHT(LEFT(RS.LineFromFile,104),3) as PERSONCODE
		, RIGHT(LEFT(RS.LineFromFile,129),25) as CARDHOLDERLASTNAME
		, RIGHT(LEFT(RS.LineFromFile,154),25) as CARDHOLDERFIRSTNAME
		, RIGHT(LEFT(RS.LineFromFile,155),1) as CARDHOLDERMIDDLEINITIAL
		, RIGHT(LEFT(RS.LineFromFile,180),25) as PATIENTLASTNAME
		, RIGHT(LEFT(RS.LineFromFile,195),15) as PATIENTFIRSTNAME
		, RIGHT(LEFT(RS.LineFromFile,203),8) as PATIENTBIRTHDATE
		, RIGHT(LEFT(RS.LineFromFile,204),1) as PATIENTSEX
		, RIGHT(LEFT(RS.LineFromFile,205),1) as RELATIONSHIPCODE
		, RIGHT(LEFT(RS.LineFromFile,215),10) as FILLER
		, RIGHT(LEFT(RS.LineFromFile,230),15) as PROVIDERID
		, RIGHT(LEFT(RS.LineFromFile,232),2) as PROVIDERIDQUALIFIER
		, RIGHT(LEFT(RS.LineFromFile,252),20) as PROVIDERNAME
		, RIGHT(LEFT(RS.LineFromFile,258),6) as NETWORKID
		, RIGHT(LEFT(RS.LineFromFile,267),9) as RXNUMBER
		, RIGHT(LEFT(RS.LineFromFile,268),1) as RXNUMBERQUALIFIER
		, RIGHT(LEFT(RS.LineFromFile,276),8) as DATEFILLED
		, RIGHT(LEFT(RS.LineFromFile,284),8) as DATEPRESCRIPTIONWRITTEN
		, RIGHT(LEFT(RS.LineFromFile,292),8) as RXCLAIMDATEPROCESSED
		, RIGHT(LEFT(RS.LineFromFile,310),18) as TRANSACTIONID
		, RIGHT(LEFT(RS.LineFromFile,311),1) as CLAIMSTATUSFLAG
		, RIGHT(LEFT(RS.LineFromFile,312),1) as CLAIMORIGINATIONFLAG
		, RIGHT(LEFT(RS.LineFromFile,313),1) as REIMBURSEMENTTYPE
		, RIGHT(LEFT(RS.LineFromFile,315),2) as NEWREFILLNUMBER
		, RIGHT(LEFT(RS.LineFromFile,317),2) as NUMBEROFREFILLSAUTHORIZED
		, RIGHT(LEFT(RS.LineFromFile,327),10) as PRICESOURCEINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,347),20) as PRODUCTID
		, RIGHT(LEFT(RS.LineFromFile,349),2) as PRODUCTIDQUALIFIER
		, RIGHT(LEFT(RS.LineFromFile,379),30) as DRUGNAME
		, RIGHT(LEFT(RS.LineFromFile,381),2) as DRUGADMINISTRATIONROUTECODE
		, RIGHT(LEFT(RS.LineFromFile,395),14) as GPICODE
		, RIGHT(LEFT(RS.LineFromFile,396),1) as MEDBMEDDINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,400),4) as FILLER2
		, RIGHT(LEFT(RS.LineFromFile,405),5) as GENERICCLASS
		, RIGHT(LEFT(RS.LineFromFile,465),60) as GENERICNAME
		, RIGHT(LEFT(RS.LineFromFile,466),1) as GENERICBRANDINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,472),6) as THERAPEUTICCLASSAHFSCODE
		, RIGHT(LEFT(RS.LineFromFile,473),1) as MULTISINGLESOURCEINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,477),4) as DRUGDOSAGEFORM
		, RIGHT(LEFT(RS.LineFromFile,487),10) as DRUGSTRENGTH
		, RIGHT(LEFT(RS.LineFromFile,489),2) as DEACLASS
		, RIGHT(LEFT(RS.LineFromFile,490),1) as COMPOUNDINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,491),1) as PRODUCTSELECTIONCODEDAW
		, RIGHT(LEFT(RS.LineFromFile,492),1) as OTHERCOVERAGE
		, RIGHT(LEFT(RS.LineFromFile,503),11) as PAYABLEQUANTITY
		, RIGHT(LEFT(RS.LineFromFile,512),9) as PHARMACYAMOUNTSUBMITTEDUC
		, RIGHT(LEFT(RS.LineFromFile,515),3) as DAYSSUPPLY
		, RIGHT(LEFT(RS.LineFromFile,524),9) as SUBMITTEDINGREDIENTCOST
		, RIGHT(LEFT(RS.LineFromFile,533),9) as INGREDIENTCOSTPAYABLE
		, RIGHT(LEFT(RS.LineFromFile,542),9) as SUBMITTEDDISPENSINGFEE
		, RIGHT(LEFT(RS.LineFromFile,551),9) as DISPENSINGFEEPAYABLE
		, RIGHT(LEFT(RS.LineFromFile,560),9) as SUBMITTEDSALESTAX
		, RIGHT(LEFT(RS.LineFromFile,569),9) as SALESTAXPAYABLE
		, RIGHT(LEFT(RS.LineFromFile,578),9) as SUBMITTEDGROSSAMOUNTDUE
		, RIGHT(LEFT(RS.LineFromFile,587),9) as AMOUNTBILLED
		, RIGHT(LEFT(RS.LineFromFile,596),9) as SUBMITTEDPATIENTPAYAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,605),9) as PATIENTPAYAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,614),9) as FLATCOPAYAMOUNTPAID
		, RIGHT(LEFT(RS.LineFromFile,623),9) as PERCENTCOPAYAMOUNTPAID
		, RIGHT(LEFT(RS.LineFromFile,628),5) as ADMINFEE
		, RIGHT(LEFT(RS.LineFromFile,629),1) as MAINTENANCEDRUGINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,639),10) as FINALPLANCODE
		, RIGHT(LEFT(RS.LineFromFile,647),8) as PLANCODEEXTENSION
		, RIGHT(LEFT(RS.LineFromFile,648),1) as FILLER3
		, RIGHT(LEFT(RS.LineFromFile,657),9) as CARDHOLDERCOPAYDIFFERENTIAL
		, RIGHT(LEFT(RS.LineFromFile,666),9) as FRONTENDDEDUCTIBLEAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,675),9) as AFTERMAXAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,684),9) as TOTALCOPAYAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,693),9) as PATIENTACCUMULATEDDEDUCTIBLEAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,696),3) as DISPENSERTYPE
		, RIGHT(LEFT(RS.LineFromFile,706),10) as AWP
		, RIGHT(LEFT(RS.LineFromFile,707),1) as AWPTYPEINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,710),3) as BILLINGREPORTINGCODE
		, RIGHT(LEFT(RS.LineFromFile,711),1) as FORMULARYINDICATORFORMULARYSTATUS
		, RIGHT(LEFT(RS.LineFromFile,714),3) as REJECTCODE1
		, RIGHT(LEFT(RS.LineFromFile,725),11) as PRIORAUTHORIZATIONNUMBER
		, RIGHT(LEFT(RS.LineFromFile,727),2) as PRIORAUTHORIZATIONREASONCODES
		, RIGHT(LEFT(RS.LineFromFile,739),12) as PAMCSCCODEANDNUMBER
		, RIGHT(LEFT(RS.LineFromFile,741),2) as BASISOFCOSTDETERMINATION
		, RIGHT(LEFT(RS.LineFromFile,756),15) as PRESCRIBERNUMBER
		, RIGHT(LEFT(RS.LineFromFile,758),2) as PRESCRIBERIDQUALIFER
		, RIGHT(LEFT(RS.LineFromFile,763),5) as PERFORMANCERXPHARMACYFEEPAID
		, RIGHT(LEFT(RS.LineFromFile,768),5) as PERFORMANCERXFEEPAID
		, RIGHT(LEFT(RS.LineFromFile,783),15) as D0RXNUMBER
		, RIGHT(LEFT(RS.LineFromFile,784),1) as RXNUMBERQUALIFIER2
		, RIGHT(LEFT(RS.LineFromFile,787),3) as ADJUSTMENTREASONCODE
		, RIGHT(LEFT(RS.LineFromFile,797),10) as ADJUSTMENTISSUEID
		, RIGHT(LEFT(RS.LineFromFile,806),9) as RebillIncentive
		, RIGHT(LEFT(RS.LineFromFile,807),1) as VaccineClaimIndicator
		, RIGHT(LEFT(RS.LineFromFile,817),10) as CareNetwork
		, RIGHT(LEFT(RS.LineFromFile,827),10) as CareQualifier
		, RIGHT(LEFT(RS.LineFromFile,835),8) as COBPrimaryPayerAmountPaid
		, RIGHT(LEFT(RS.LineFromFile,846),11) as AppliedHRAAmount
		, RIGHT(LEFT(RS.LineFromFile,854),8) as BILLINGCYCLEENDDATE
		, RIGHT(LEFT(RS.LineFromFile,855),1) as MAINTENANCECHOICEINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,863),8) as OPARAmount
		, RIGHT(LEFT(RS.LineFromFile,865),2) as CB5Qualifier
		, RIGHT(LEFT(RS.LineFromFile,874),9) as CB5OTHAmount1
		, RIGHT(LEFT(RS.LineFromFile,876),2) as CB5Qualifier2
		, RIGHT(LEFT(RS.LineFromFile,885),9) as CB5OTHAmount2
		, RIGHT(LEFT(RS.LineFromFile,887),2) as CB5Qualifier3
		, RIGHT(LEFT(RS.LineFromFile,896),9) as CB5OTHAmount3
		, RIGHT(LEFT(RS.LineFromFile,905),9) as PD6ClientTotalOtherAmount
		, RIGHT(LEFT(RS.LineFromFile,914),9) as PD6BuyTotalOtherAmount
		, RIGHT(LEFT(RS.LineFromFile,916),2) as DiagnosisCodeQualifier
		, RIGHT(LEFT(RS.LineFromFile,931),15) as DiagnosisCode
		, RIGHT(RS.LineFromFile,19) as FILLER4
	FROM RawSource.DummyData_Brooke_File1_BCP RS
	WHERE RS.LineNumber > 1
	AND RS.LineNumber < @NumberOfLines

END
;
GO






USE HealthStrategy
GO
CREATE PROC dbo.ParseDataFile2
AS
BEGIN
	DECLARE @Filename VARCHAR(50) = 'DummyData_Brooke_File2.txt';
	DECLARE @NumberOfLines INT;
	DECLARE @sqlQuery NVARCHAR(4000);
	DECLARE @ParmDefinition NVARCHAR(500);

	SELECT @NumberOfLines = MAX(RS.LineNumber) 
	FROM RawSource.DummyData_Brooke_File2_BCP RS
	;

	-- Put header into table
	INSERT INTO dbo.Dummy_Data_BCP_Header(
		FILENAME,
		RECORDIDENTIFIER,
		RUNDATE,
		SENDINGCOMPANYNAME,
		CYCLESTARTDATE,
		CYCLEENDDATE,
		FILLER
	)
	SELECT
	@Filename as Filename
	, LEFT(RS.LineFromFile, 1) as RecordIdentifier
	, RIGHT(LEFT(RS.LineFromFile, 9), 8) as RunDate
	, RIGHT(LEFT(RS.LineFromFile, 29), 20) as SendingCompanyName
	, RIGHT(LEFT(RS.LineFromFile, 37), 8) as CycleStartDate
	, RIGHT(LEFT(RS.LineFromFile, 45), 8) as CycleEndDate
	, RIGHT(RS.LineFromFile, 905) as Filler
	FROM RawSource.DummyData_Brooke_File2_BCP RS
	WHERE RS.LineNumber = 1
	;
	
	--Put trailer into table
	INSERT INTO dbo.Dummy_Data_BCP_Trailer(
		FILENAME,
		RECORDIDENTIFIER,
		TOTALNUMBEROFCLAIMS,
		TOTALAMOUNTPAYABLE,
		TOTALADMINFEEAMOUNT,
		FILLER
	)
	SELECT
	@Filename as Filename
	, LEFT(RS.LineFromFile, 1) as RecordIdentifier
	, RIGHT(LEFT(RS.LineFromFile, 10), 9) as TotalNumberOfClaims
	, RIGHT(LEFT(RS.LineFromFile, 24), 14) as TotalAmountPayable
	, RIGHT(LEFT(RS.LineFromFile, 33), 9) as TotalAdminFeeAmount
	, RIGHT(RS.LineFromFile, 917) as Filler
	FROM RawSource.DummyData_Brooke_File2_BCP RS
	WHERE RS.LineNumber = @NumberOfLines
	;

	-- PARSE DATA LINES INTO DESTINATION TABLE
	INSERT INTO dbo.Dummy_Data_BCP_01_Native
	SELECT
		LEFT(RS.LineFromFile, 1) as RecordIdentifier
		, RIGHT(LEFT(RS.LineFromFile,21),20) as CARRIERID
		, RIGHT(LEFT(RS.LineFromFile,36),15) as ACCOUNTIDGROUPEXTENSIONCODE
		, RIGHT(LEFT(RS.LineFromFile,51),15) as GROUPID
		, RIGHT(LEFT(RS.LineFromFile,71),20) as CARDHOLDERMEMBERID
		, RIGHT(LEFT(RS.LineFromFile,91),20) as ALTERNATEID
		, RIGHT(LEFT(RS.LineFromFile,101),10) as CAREFACILITYID
		, RIGHT(LEFT(RS.LineFromFile,104),3) as PERSONCODE
		, RIGHT(LEFT(RS.LineFromFile,129),25) as CARDHOLDERLASTNAME
		, RIGHT(LEFT(RS.LineFromFile,154),25) as CARDHOLDERFIRSTNAME
		, RIGHT(LEFT(RS.LineFromFile,155),1) as CARDHOLDERMIDDLEINITIAL
		, RIGHT(LEFT(RS.LineFromFile,180),25) as PATIENTLASTNAME
		, RIGHT(LEFT(RS.LineFromFile,195),15) as PATIENTFIRSTNAME
		, RIGHT(LEFT(RS.LineFromFile,203),8) as PATIENTBIRTHDATE
		, RIGHT(LEFT(RS.LineFromFile,204),1) as PATIENTSEX
		, RIGHT(LEFT(RS.LineFromFile,205),1) as RELATIONSHIPCODE
		, RIGHT(LEFT(RS.LineFromFile,215),10) as FILLER
		, RIGHT(LEFT(RS.LineFromFile,230),15) as PROVIDERID
		, RIGHT(LEFT(RS.LineFromFile,232),2) as PROVIDERIDQUALIFIER
		, RIGHT(LEFT(RS.LineFromFile,252),20) as PROVIDERNAME
		, RIGHT(LEFT(RS.LineFromFile,258),6) as NETWORKID
		, RIGHT(LEFT(RS.LineFromFile,267),9) as RXNUMBER
		, RIGHT(LEFT(RS.LineFromFile,268),1) as RXNUMBERQUALIFIER
		, RIGHT(LEFT(RS.LineFromFile,276),8) as DATEFILLED
		, RIGHT(LEFT(RS.LineFromFile,284),8) as DATEPRESCRIPTIONWRITTEN
		, RIGHT(LEFT(RS.LineFromFile,292),8) as RXCLAIMDATEPROCESSED
		, RIGHT(LEFT(RS.LineFromFile,310),18) as TRANSACTIONID
		, RIGHT(LEFT(RS.LineFromFile,311),1) as CLAIMSTATUSFLAG
		, RIGHT(LEFT(RS.LineFromFile,312),1) as CLAIMORIGINATIONFLAG
		, RIGHT(LEFT(RS.LineFromFile,313),1) as REIMBURSEMENTTYPE
		, RIGHT(LEFT(RS.LineFromFile,315),2) as NEWREFILLNUMBER
		, RIGHT(LEFT(RS.LineFromFile,317),2) as NUMBEROFREFILLSAUTHORIZED
		, RIGHT(LEFT(RS.LineFromFile,327),10) as PRICESOURCEINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,347),20) as PRODUCTID
		, RIGHT(LEFT(RS.LineFromFile,349),2) as PRODUCTIDQUALIFIER
		, RIGHT(LEFT(RS.LineFromFile,379),30) as DRUGNAME
		, RIGHT(LEFT(RS.LineFromFile,381),2) as DRUGADMINISTRATIONROUTECODE
		, RIGHT(LEFT(RS.LineFromFile,395),14) as GPICODE
		, RIGHT(LEFT(RS.LineFromFile,396),1) as MEDBMEDDINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,400),4) as FILLER2
		, RIGHT(LEFT(RS.LineFromFile,405),5) as GENERICCLASS
		, RIGHT(LEFT(RS.LineFromFile,465),60) as GENERICNAME
		, RIGHT(LEFT(RS.LineFromFile,466),1) as GENERICBRANDINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,472),6) as THERAPEUTICCLASSAHFSCODE
		, RIGHT(LEFT(RS.LineFromFile,473),1) as MULTISINGLESOURCEINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,477),4) as DRUGDOSAGEFORM
		, RIGHT(LEFT(RS.LineFromFile,487),10) as DRUGSTRENGTH
		, RIGHT(LEFT(RS.LineFromFile,489),2) as DEACLASS
		, RIGHT(LEFT(RS.LineFromFile,490),1) as COMPOUNDINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,491),1) as PRODUCTSELECTIONCODEDAW
		, RIGHT(LEFT(RS.LineFromFile,492),1) as OTHERCOVERAGE
		, RIGHT(LEFT(RS.LineFromFile,503),11) as PAYABLEQUANTITY
		, RIGHT(LEFT(RS.LineFromFile,512),9) as PHARMACYAMOUNTSUBMITTEDUC
		, RIGHT(LEFT(RS.LineFromFile,515),3) as DAYSSUPPLY
		, RIGHT(LEFT(RS.LineFromFile,524),9) as SUBMITTEDINGREDIENTCOST
		, RIGHT(LEFT(RS.LineFromFile,533),9) as INGREDIENTCOSTPAYABLE
		, RIGHT(LEFT(RS.LineFromFile,542),9) as SUBMITTEDDISPENSINGFEE
		, RIGHT(LEFT(RS.LineFromFile,551),9) as DISPENSINGFEEPAYABLE
		, RIGHT(LEFT(RS.LineFromFile,560),9) as SUBMITTEDSALESTAX
		, RIGHT(LEFT(RS.LineFromFile,569),9) as SALESTAXPAYABLE
		, RIGHT(LEFT(RS.LineFromFile,578),9) as SUBMITTEDGROSSAMOUNTDUE
		, RIGHT(LEFT(RS.LineFromFile,587),9) as AMOUNTBILLED
		, RIGHT(LEFT(RS.LineFromFile,596),9) as SUBMITTEDPATIENTPAYAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,605),9) as PATIENTPAYAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,614),9) as FLATCOPAYAMOUNTPAID
		, RIGHT(LEFT(RS.LineFromFile,623),9) as PERCENTCOPAYAMOUNTPAID
		, RIGHT(LEFT(RS.LineFromFile,628),5) as ADMINFEE
		, RIGHT(LEFT(RS.LineFromFile,629),1) as MAINTENANCEDRUGINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,639),10) as FINALPLANCODE
		, RIGHT(LEFT(RS.LineFromFile,647),8) as PLANCODEEXTENSION
		, RIGHT(LEFT(RS.LineFromFile,648),1) as FILLER3
		, RIGHT(LEFT(RS.LineFromFile,657),9) as CARDHOLDERCOPAYDIFFERENTIAL
		, RIGHT(LEFT(RS.LineFromFile,666),9) as FRONTENDDEDUCTIBLEAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,675),9) as AFTERMAXAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,684),9) as TOTALCOPAYAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,693),9) as PATIENTACCUMULATEDDEDUCTIBLEAMOUNT
		, RIGHT(LEFT(RS.LineFromFile,696),3) as DISPENSERTYPE
		, RIGHT(LEFT(RS.LineFromFile,706),10) as AWP
		, RIGHT(LEFT(RS.LineFromFile,707),1) as AWPTYPEINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,710),3) as BILLINGREPORTINGCODE
		, RIGHT(LEFT(RS.LineFromFile,711),1) as FORMULARYINDICATORFORMULARYSTATUS
		, RIGHT(LEFT(RS.LineFromFile,714),3) as REJECTCODE1
		, RIGHT(LEFT(RS.LineFromFile,725),11) as PRIORAUTHORIZATIONNUMBER
		, RIGHT(LEFT(RS.LineFromFile,727),2) as PRIORAUTHORIZATIONREASONCODES
		, RIGHT(LEFT(RS.LineFromFile,739),12) as PAMCSCCODEANDNUMBER
		, RIGHT(LEFT(RS.LineFromFile,741),2) as BASISOFCOSTDETERMINATION
		, RIGHT(LEFT(RS.LineFromFile,756),15) as PRESCRIBERNUMBER
		, RIGHT(LEFT(RS.LineFromFile,758),2) as PRESCRIBERIDQUALIFER
		, RIGHT(LEFT(RS.LineFromFile,763),5) as PERFORMANCERXPHARMACYFEEPAID
		, RIGHT(LEFT(RS.LineFromFile,768),5) as PERFORMANCERXFEEPAID
		, RIGHT(LEFT(RS.LineFromFile,783),15) as D0RXNUMBER
		, RIGHT(LEFT(RS.LineFromFile,784),1) as RXNUMBERQUALIFIER2
		, RIGHT(LEFT(RS.LineFromFile,787),3) as ADJUSTMENTREASONCODE
		, RIGHT(LEFT(RS.LineFromFile,797),10) as ADJUSTMENTISSUEID
		, RIGHT(LEFT(RS.LineFromFile,806),9) as RebillIncentive
		, RIGHT(LEFT(RS.LineFromFile,807),1) as VaccineClaimIndicator
		, RIGHT(LEFT(RS.LineFromFile,817),10) as CareNetwork
		, RIGHT(LEFT(RS.LineFromFile,827),10) as CareQualifier
		, RIGHT(LEFT(RS.LineFromFile,835),8) as COBPrimaryPayerAmountPaid
		, RIGHT(LEFT(RS.LineFromFile,846),11) as AppliedHRAAmount
		, RIGHT(LEFT(RS.LineFromFile,854),8) as BILLINGCYCLEENDDATE
		, RIGHT(LEFT(RS.LineFromFile,855),1) as MAINTENANCECHOICEINDICATOR
		, RIGHT(LEFT(RS.LineFromFile,863),8) as OPARAmount
		, RIGHT(LEFT(RS.LineFromFile,865),2) as CB5Qualifier
		, RIGHT(LEFT(RS.LineFromFile,874),9) as CB5OTHAmount1
		, RIGHT(LEFT(RS.LineFromFile,876),2) as CB5Qualifier2
		, RIGHT(LEFT(RS.LineFromFile,885),9) as CB5OTHAmount2
		, RIGHT(LEFT(RS.LineFromFile,887),2) as CB5Qualifier3
		, RIGHT(LEFT(RS.LineFromFile,896),9) as CB5OTHAmount3
		, RIGHT(LEFT(RS.LineFromFile,905),9) as PD6ClientTotalOtherAmount
		, RIGHT(LEFT(RS.LineFromFile,914),9) as PD6BuyTotalOtherAmount
		, RIGHT(LEFT(RS.LineFromFile,916),2) as DiagnosisCodeQualifier
		, RIGHT(LEFT(RS.LineFromFile,931),15) as DiagnosisCode
		, RIGHT(RS.LineFromFile,19) as FILLER4
	FROM RawSource.DummyData_Brooke_File2_BCP RS
	WHERE RS.LineNumber > 1
	AND RS.LineNumber < @NumberOfLines

END






EXEC dbo.ParseDataFile1
;
GO
EXEC dbo.ParseDataFile2
;
GO









SELECT TOP 10 * FROM dbo.Dummy_Data_BCP_Header;
SELECT TOP 10 * FROM dbo.Dummy_Data_BCP_00_Native;
SELECT TOP 10 * FROM dbo.Dummy_Data_BCP_01_Native;
SELECT TOP 10 * FROM dbo.Dummy_Data_BCP_Trailer;



















USE HealthStrategy
;
GO
CREATE FUNCTION dbo.ConvertOverpunch (@ValueToConvert VARCHAR(100))
RETURNS BIGINT
AS
BEGIN
	DECLARE @ReturnValue BIGINT;

	SET @ReturnValue = CAST(LEFT(@ValueToConvert, LEN(@ValueToConvert) - 1) AS BIGINT) * 10
	+ 
		IIF(
			ISNUMERIC(RIGHT(@ValueToConvert, 1)) = 1 
			, CAST(RIGHT(@ValueToConvert, 1) AS INT)
			, IIF (
				RIGHT(@ValueToConvert, 1) IN ('{','}')
				, 0
				, IIF (
					RIGHT(@ValueToConvert, 1) < 'J'
					, ASCII(RIGHT(@ValueToConvert, 1)) - ASCII('@')
					, ASCII('I') - ASCII(RIGHT(@ValueToConvert, 1))
				)
			)
		)
	;

	RETURN @ReturnValue
END
GO
















































USE HealthStrategy
;
GO
CREATE VIEW dbo.Dummy_Data_BCP_Transformed
AS
SELECT
RECORDIDENTIFIER
, CARRIERID
, ACCOUNTIDGROUPEXTENSIONCODE
, GROUPID
, CARDHOLDERMEMBERID
, ALTERNATEID
, CAREFACILITYID
, PERSONCODE
, CARDHOLDERLASTNAME
, CARDHOLDERFIRSTNAME
, CARDHOLDERMIDDLEINITIAL
, PATIENTLASTNAME
, PATIENTFIRSTNAME
, PATIENTBIRTHDATE AS PATIENTBIRTHDATE_RAW
, CAST(PATIENTBIRTHDATE AS DATE) AS PATIENTBIRTHDATE
, PATIENTSEX
, RELATIONSHIPCODE
, FILLER
, PROVIDERID
, PROVIDERIDQUALIFIER
, PROVIDERNAME
, NETWORKID
, RXNUMBER
, RXNUMBERQUALIFIER
, DATEFILLED AS DATEFILLED_RAW
, CAST(DATEFILLED AS DATE) AS DATEFILLED
, DATEPRESCRIPTIONWRITTEN AS DATEPRESCRIPTIONWRITTEN_RAW
, CAST(DATEPRESCRIPTIONWRITTEN AS DATE) AS DATEPRESCRIPTIONWRITTEN
, RXCLAIMDATEPROCESSED AS RXCLAIMDATEPROCESSED_RAW
, CAST(RXCLAIMDATEPROCESSED AS DATE) AS RXCLAIMDATEPROCESSED
, TRANSACTIONID
, CLAIMSTATUSFLAG
, CLAIMORIGINATIONFLAG
, REIMBURSEMENTTYPE
, NEWREFILLNUMBER
, NUMBEROFREFILLSAUTHORIZED
, PRICESOURCEINDICATOR
, PRODUCTID
, PRODUCTIDQUALIFIER
, DRUGNAME
, DRUGADMINISTRATIONROUTECODE
, GPICODE
, MEDBMEDDINDICATOR
, FILLER2
, GENERICCLASS
, GENERICNAME
, GENERICBRANDINDICATOR
, THERAPEUTICCLASSAHFSCODE
, MULTISINGLESOURCEINDICATOR
, DRUGDOSAGEFORM
, DRUGSTRENGTH
, DEACLASS
, COMPOUNDINDICATOR
, PRODUCTSELECTIONCODEDAW
, OTHERCOVERAGE
, PAYABLEQUANTITY AS PAYABLEQUANTITY_RAW
, dbo.ConvertOverpunch(PAYABLEQUANTITY) / 1000.00 AS PAYABLEQUANTITY
, PHARMACYAMOUNTSUBMITTEDUC
, DAYSSUPPLY AS DAYSSUPPLY_RAW
, CAST(dbo.ConvertOverpunch(DAYSSUPPLY) AS INT) AS DAYSSUPPLY
, SUBMITTEDINGREDIENTCOST
, INGREDIENTCOSTPAYABLE AS INGREDIENTCOSTPAYABLE_RAW
, dbo.ConvertOverpunch(INGREDIENTCOSTPAYABLE) / 100.00 AS INGREDIENTCOSTPAYABLE
, SUBMITTEDDISPENSINGFEE
, DISPENSINGFEEPAYABLE
, SUBMITTEDSALESTAX
, SALESTAXPAYABLE
, SUBMITTEDGROSSAMOUNTDUE
, AMOUNTBILLED
, SUBMITTEDPATIENTPAYAMOUNT
, PATIENTPAYAMOUNT
, FLATCOPAYAMOUNTPAID
, PERCENTCOPAYAMOUNTPAID
, ADMINFEE
, MAINTENANCEDRUGINDICATOR
, FINALPLANCODE
, PLANCODEEXTENSION
, FILLER3
, CARDHOLDERCOPAYDIFFERENTIAL
, FRONTENDDEDUCTIBLEAMOUNT
, AFTERMAXAMOUNT
, TOTALCOPAYAMOUNT
, PATIENTACCUMULATEDDEDUCTIBLEAMOUNT
, DISPENSERTYPE
, AWP AS AWP_RAW
, dbo.ConvertOverpunch(AWP) / 100000.00 AS AWP
, AWPTYPEINDICATOR
, BILLINGREPORTINGCODE
, FORMULARYINDICATORFORMULARYSTATUS
, REJECTCODE1
, PRIORAUTHORIZATIONNUMBER
, PRIORAUTHORIZATIONREASONCODES
, PAMCSCCODEANDNUMBER
, BASISOFCOSTDETERMINATION
, PRESCRIBERNUMBER
, PRESCRIBERIDQUALIFER
, PERFORMANCERXPHARMACYFEEPAID
, PERFORMANCERXFEEPAID
, D0RXNUMBER
, RXNUMBERQUALIFIER2
, ADJUSTMENTREASONCODE
, ADJUSTMENTISSUEID
, RebillIncentive
, VaccineClaimIndicator
, CareNetwork
, CareQualifier
, COBPrimaryPayerAmountPaid
, AppliedHRAAmount
, BILLINGCYCLEENDDATE AS BILLINGCYCLEENDDATE_RAW
, CASE WHEN BILLINGCYCLEENDDATE = 0 THEN CAST('9999-12-31' AS DATE) ELSE CAST(BILLINGCYCLEENDDATE AS DATE) END AS BILLINGCYCLEENDDATE
, MAINTENANCECHOICEINDICATOR
, OPARAmount
, CB5Qualifier
, CB5OTHAmount1
, CB5Qualifier2
, CB5OTHAmount2
, CB5Qualifier3
, CB5OTHAmount3
, PD6ClientTotalOtherAmount
, PD6BuyTotalOtherAmount
, DiagnosisCodeQualifier
, DiagnosisCode
, FILLER4
, MA1.Multi_Source_Code
, MA1.Brand_Name_Code
, MR.Effective_Date
, MR.AWP_Unit_Price
, CASE
	WHEN MA1.Multi_Source_Code = 'Y' OR MA1.Brand_Name_Code = 'G' THEN 'G'
	ELSE 'B'
END AS BG_Ind

FROM dbo.Dummy_Data_BCP_00_Native D
LEFT JOIN dbo.MedispanA1_Sample MA1 ON D.PRODUCTID = MA1.NDC_UPC_HRI 
	AND D.PRODUCTIDQUALIFIER = '03'
LEFT JOIN dbo.MedispanR_Sample MR ON D.PRODUCTID = MR.NDC_UPC_HRI 
	AND D.PRODUCTIDQUALIFIER = '03'
	AND D.DATEFILLED >= MR.Effective_Date
LEFT JOIN dbo.MedispanR_Sample MR2 ON MR.NDC_UPC_HRI = MR2.NDC_UPC_HRI
	AND MR.Effective_Date < MR2.Effective_Date
	AND D.DATEFILLED >= MR2.Effective_Date

WHERE 
-- Filter out the MedispanR records that are NOT the most recent based on the date filled field
MR2.NDC_UPC_HRI IS NULL

UNION ALL

SELECT
RECORDIDENTIFIER
, CARRIERID
, ACCOUNTIDGROUPEXTENSIONCODE
, GROUPID
, CARDHOLDERMEMBERID
, ALTERNATEID
, CAREFACILITYID
, PERSONCODE
, CARDHOLDERLASTNAME
, CARDHOLDERFIRSTNAME
, CARDHOLDERMIDDLEINITIAL
, PATIENTLASTNAME
, PATIENTFIRSTNAME
, PATIENTBIRTHDATE AS PATIENTBIRTHDATE_RAW
, CAST(PATIENTBIRTHDATE AS DATE) AS PATIENTBIRTHDATE
, PATIENTSEX
, RELATIONSHIPCODE
, FILLER
, PROVIDERID
, PROVIDERIDQUALIFIER
, PROVIDERNAME
, NETWORKID
, RXNUMBER
, RXNUMBERQUALIFIER
, DATEFILLED AS DATEFILLED_RAW
, CAST(DATEFILLED AS DATE) AS DATEFILLED
, DATEPRESCRIPTIONWRITTEN AS DATEPRESCRIPTIONWRITTEN_RAW
, CAST(DATEPRESCRIPTIONWRITTEN AS DATE) AS DATEPRESCRIPTIONWRITTEN
, RXCLAIMDATEPROCESSED AS RXCLAIMDATEPROCESSED_RAW
, CAST(RXCLAIMDATEPROCESSED AS DATE) AS RXCLAIMDATEPROCESSED
, TRANSACTIONID
, CLAIMSTATUSFLAG
, CLAIMORIGINATIONFLAG
, REIMBURSEMENTTYPE
, NEWREFILLNUMBER
, NUMBEROFREFILLSAUTHORIZED
, PRICESOURCEINDICATOR
, PRODUCTID
, PRODUCTIDQUALIFIER
, DRUGNAME
, DRUGADMINISTRATIONROUTECODE
, GPICODE
, MEDBMEDDINDICATOR
, FILLER2
, GENERICCLASS
, GENERICNAME
, GENERICBRANDINDICATOR
, THERAPEUTICCLASSAHFSCODE
, MULTISINGLESOURCEINDICATOR
, DRUGDOSAGEFORM
, DRUGSTRENGTH
, DEACLASS
, COMPOUNDINDICATOR
, PRODUCTSELECTIONCODEDAW
, OTHERCOVERAGE
, PAYABLEQUANTITY AS PAYABLEQUANTITY_RAW
, dbo.ConvertOverpunch(PAYABLEQUANTITY) / 1000.00 AS PAYABLEQUANTITY
, PHARMACYAMOUNTSUBMITTEDUC
, DAYSSUPPLY AS DAYSSUPPLY_RAW
, CAST(dbo.ConvertOverpunch(DAYSSUPPLY) AS INT) AS DAYSSUPPLY
, SUBMITTEDINGREDIENTCOST
, INGREDIENTCOSTPAYABLE AS INGREDIENTCOSTPAYABLE_RAW
, dbo.ConvertOverpunch(INGREDIENTCOSTPAYABLE) / 100.00 AS INGREDIENTCOSTPAYABLE
, SUBMITTEDDISPENSINGFEE
, DISPENSINGFEEPAYABLE
, SUBMITTEDSALESTAX
, SALESTAXPAYABLE
, SUBMITTEDGROSSAMOUNTDUE
, AMOUNTBILLED
, SUBMITTEDPATIENTPAYAMOUNT
, PATIENTPAYAMOUNT
, FLATCOPAYAMOUNTPAID
, PERCENTCOPAYAMOUNTPAID
, ADMINFEE
, MAINTENANCEDRUGINDICATOR
, FINALPLANCODE
, PLANCODEEXTENSION
, FILLER3
, CARDHOLDERCOPAYDIFFERENTIAL
, FRONTENDDEDUCTIBLEAMOUNT
, AFTERMAXAMOUNT
, TOTALCOPAYAMOUNT
, PATIENTACCUMULATEDDEDUCTIBLEAMOUNT
, DISPENSERTYPE
, AWP AS AWP_RAW
, dbo.ConvertOverpunch(AWP) / 100000.00 AS AWP
, AWPTYPEINDICATOR
, BILLINGREPORTINGCODE
, FORMULARYINDICATORFORMULARYSTATUS
, REJECTCODE1
, PRIORAUTHORIZATIONNUMBER
, PRIORAUTHORIZATIONREASONCODES
, PAMCSCCODEANDNUMBER
, BASISOFCOSTDETERMINATION
, PRESCRIBERNUMBER
, PRESCRIBERIDQUALIFER
, PERFORMANCERXPHARMACYFEEPAID
, PERFORMANCERXFEEPAID
, D0RXNUMBER
, RXNUMBERQUALIFIER2
, ADJUSTMENTREASONCODE
, ADJUSTMENTISSUEID
, RebillIncentive
, VaccineClaimIndicator
, CareNetwork
, CareQualifier
, COBPrimaryPayerAmountPaid
, AppliedHRAAmount
, BILLINGCYCLEENDDATE AS BILLINGCYCLEENDDATE_RAW
, CASE WHEN BILLINGCYCLEENDDATE = 0 THEN CAST('9999-12-31' AS DATE) ELSE CAST(BILLINGCYCLEENDDATE AS DATE) END AS BILLINGCYCLEENDDATE
, MAINTENANCECHOICEINDICATOR
, OPARAmount
, CB5Qualifier
, CB5OTHAmount1
, CB5Qualifier2
, CB5OTHAmount2
, CB5Qualifier3
, CB5OTHAmount3
, PD6ClientTotalOtherAmount
, PD6BuyTotalOtherAmount
, DiagnosisCodeQualifier
, DiagnosisCode
, FILLER4
, MA1.Multi_Source_Code
, MA1.Brand_Name_Code
, MR.Effective_Date
, MR.AWP_Unit_Price
, CASE
	WHEN MA1.Multi_Source_Code = 'Y' OR MA1.Brand_Name_Code = 'G' THEN 'G'
	ELSE 'B'
END AS BG_Ind

FROM dbo.Dummy_Data_BCP_01_Native D
LEFT JOIN dbo.MedispanA1_Sample MA1 ON D.PRODUCTID = MA1.NDC_UPC_HRI 
	AND D.PRODUCTIDQUALIFIER = '03'
LEFT JOIN dbo.MedispanR_Sample MR ON D.PRODUCTID = MR.NDC_UPC_HRI 
	AND D.PRODUCTIDQUALIFIER = '03'
	AND D.DATEFILLED >= MR.Effective_Date
LEFT JOIN dbo.MedispanR_Sample MR2 ON MR.NDC_UPC_HRI = MR2.NDC_UPC_HRI
	AND MR.Effective_Date < MR2.Effective_Date
	AND D.DATEFILLED >= MR2.Effective_Date

WHERE 
-- Filter out the MedispanR records that are NOT the most recent based on the date filled field
MR2.NDC_UPC_HRI IS NULL
;























USE [HealthStrategy]
GO

CREATE TABLE [dbo].[Dummy_Data_BCP_05_Staging](
	[RECORDIDENTIFIER] [char](1) NULL,
	[CARRIERID] [char](20) NULL,
	[ACCOUNTIDGROUPEXTENSIONCODE] [char](15) NULL,
	[GROUPID] [char](15) NULL,
	[CARDHOLDERMEMBERID] [char](20) NULL,
	[ALTERNATEID] [char](20) NULL,
	[CAREFACILITYID] [char](10) NULL,
	[PERSONCODE] [char](3) NULL,
	[CARDHOLDERLASTNAME] [char](25) NULL,
	[CARDHOLDERFIRSTNAME] [char](25) NULL,
	[CARDHOLDERMIDDLEINITIAL] [char](1) NULL,
	[PATIENTLASTNAME] [char](25) NULL,
	[PATIENTFIRSTNAME] [char](15) NULL,
	[PATIENTBIRTHDATE_RAW] [char](8) NULL,
	[PATIENTBIRTHDATE] [date] NULL,
	[PATIENTSEX] [char](1) NULL,
	[RELATIONSHIPCODE] [char](1) NULL,
	[FILLER] [char](10) NULL,
	[PROVIDERID] [char](15) NULL,
	[PROVIDERIDQUALIFIER] [char](2) NULL,
	[PROVIDERNAME] [char](20) NULL,
	[NETWORKID] [char](6) NULL,
	[RXNUMBER] [char](9) NULL,
	[RXNUMBERQUALIFIER] [char](1) NULL,
	[DATEFILLED_RAW] [char](8) NULL,
	[DATEFILLED] [date] NULL,
	[DATEPRESCRIPTIONWRITTEN_RAW] [char](8) NULL,
	[DATEPRESCRIPTIONWRITTEN] [date] NULL,
	[RXCLAIMDATEPROCESSED_RAW] [char](8) NULL,
	[RXCLAIMDATEPROCESSED] [date] NULL,
	[TRANSACTIONID] [char](18) NULL,
	[CLAIMSTATUSFLAG] [char](1) NULL,
	[CLAIMORIGINATIONFLAG] [char](1) NULL,
	[REIMBURSEMENTTYPE] [char](1) NULL,
	[NEWREFILLNUMBER] [char](2) NULL,
	[NUMBEROFREFILLSAUTHORIZED] [char](2) NULL,
	[PRICESOURCEINDICATOR] [char](10) NULL,
	[PRODUCTID] [char](20) NULL,
	[PRODUCTIDQUALIFIER] [char](2) NULL,
	[DRUGNAME] [char](30) NULL,
	[DRUGADMINISTRATIONROUTECODE] [char](2) NULL,
	[GPICODE] [char](14) NULL,
	[MEDBMEDDINDICATOR] [char](1) NULL,
	[FILLER2] [char](4) NULL,
	[GENERICCLASS] [char](5) NULL,
	[GENERICNAME] [char](60) NULL,
	[GENERICBRANDINDICATOR] [char](1) NULL,
	[THERAPEUTICCLASSAHFSCODE] [char](6) NULL,
	[MULTISINGLESOURCEINDICATOR] [char](1) NULL,
	[DRUGDOSAGEFORM] [char](4) NULL,
	[DRUGSTRENGTH] [char](10) NULL,
	[DEACLASS] [char](2) NULL,
	[COMPOUNDINDICATOR] [char](1) NULL,
	[PRODUCTSELECTIONCODEDAW] [char](1) NULL,
	[OTHERCOVERAGE] [char](1) NULL,
	[PAYABLEQUANTITY_RAW] [char](11) NULL,
	[PAYABLEQUANTITY] [numeric](28, 7) NULL,
	[PHARMACYAMOUNTSUBMITTEDUC] [char](9) NULL,
	[DAYSSUPPLY_RAW] [char](3) NULL,
	[DAYSSUPPLY] [int] NULL,
	[SUBMITTEDINGREDIENTCOST] [char](9) NULL,
	[INGREDIENTCOSTPAYABLE_RAW] [char](9) NULL,
	[INGREDIENTCOSTPAYABLE] [numeric](27, 6) NULL,
	[SUBMITTEDDISPENSINGFEE] [char](9) NULL,
	[DISPENSINGFEEPAYABLE] [char](9) NULL,
	[SUBMITTEDSALESTAX] [char](9) NULL,
	[SALESTAXPAYABLE] [char](9) NULL,
	[SUBMITTEDGROSSAMOUNTDUE] [char](9) NULL,
	[AMOUNTBILLED] [char](9) NULL,
	[SUBMITTEDPATIENTPAYAMOUNT] [char](9) NULL,
	[PATIENTPAYAMOUNT] [char](9) NULL,
	[FLATCOPAYAMOUNTPAID] [char](9) NULL,
	[PERCENTCOPAYAMOUNTPAID] [char](9) NULL,
	[ADMINFEE] [char](5) NULL,
	[MAINTENANCEDRUGINDICATOR] [char](1) NULL,
	[FINALPLANCODE] [char](10) NULL,
	[PLANCODEEXTENSION] [char](8) NULL,
	[FILLER3] [char](1) NULL,
	[CARDHOLDERCOPAYDIFFERENTIAL] [char](9) NULL,
	[FRONTENDDEDUCTIBLEAMOUNT] [char](9) NULL,
	[AFTERMAXAMOUNT] [char](9) NULL,
	[TOTALCOPAYAMOUNT] [char](9) NULL,
	[PATIENTACCUMULATEDDEDUCTIBLEAMOUNT] [char](9) NULL,
	[DISPENSERTYPE] [char](3) NULL,
	[AWP_RAW] [char](10) NULL,
	[AWP] [numeric](30, 9) NULL,
	[AWPTYPEINDICATOR] [char](1) NULL,
	[BILLINGREPORTINGCODE] [char](3) NULL,
	[FORMULARYINDICATORFORMULARYSTATUS] [char](1) NULL,
	[REJECTCODE1] [char](3) NULL,
	[PRIORAUTHORIZATIONNUMBER] [char](11) NULL,
	[PRIORAUTHORIZATIONREASONCODES] [char](2) NULL,
	[PAMCSCCODEANDNUMBER] [char](12) NULL,
	[BASISOFCOSTDETERMINATION] [char](2) NULL,
	[PRESCRIBERNUMBER] [char](15) NULL,
	[PRESCRIBERIDQUALIFER] [char](2) NULL,
	[PERFORMANCERXPHARMACYFEEPAID] [char](5) NULL,
	[PERFORMANCERXFEEPAID] [char](5) NULL,
	[D0RXNUMBER] [char](15) NULL,
	[RXNUMBERQUALIFIER2] [char](1) NULL,
	[ADJUSTMENTREASONCODE] [char](3) NULL,
	[ADJUSTMENTISSUEID] [char](10) NULL,
	[REBILLINCENTIVE] [char](9) NULL,
	[VACCINECLAIMINDICATOR] [char](1) NULL,
	[CARENETWORK] [char](10) NULL,
	[CAREQUALIFIER] [char](10) NULL,
	[COBPRIMARYPAYERAMOUNTPAID] [char](8) NULL,
	[APPLIEDHRAAMOUNT] [char](11) NULL,
	[BILLINGCYCLEENDDATE_RAW] [char](8) NULL,
	[BILLINGCYCLEENDDATE] [date] NULL,
	[MAINTENANCECHOICEINDICATOR] [char](1) NULL,
	[OPARAMOUNT] [char](8) NULL,
	[CB5QUALIFIER] [char](2) NULL,
	[CB5OTHAMOUNT1] [char](9) NULL,
	[CB5QUALIFIER2] [char](2) NULL,
	[CB5OTHAMOUNT2] [char](9) NULL,
	[CB5QUALIFIER3] [char](2) NULL,
	[CB5OTHAMOUNT3] [char](9) NULL,
	[PD6CLIENTTOTALOTHERAMOUNT] [char](9) NULL,
	[PD6BUYTOTALOTHERAMOUNT] [char](9) NULL,
	[DIAGNOSISCODEQUALIFIER] [char](2) NULL,
	[DIAGNOSISCODE] [char](15) NULL,
	[FILLER4] [char](19) NULL,
	[Multi_Source_Code] [nvarchar](255) NULL,
	[Brand_Name_Code] [nvarchar](255) NULL,
	[Effective_Date] [nvarchar](255) NULL,
	[AWP_Unit_Price] [float] NULL,
	[BG_Ind] [varchar](1) NOT NULL
) ON [PRIMARY]
GO




















INSERT INTO dbo.Dummy_Data_BCP_05_Staging
SELECT *
FROM dbo.Dummy_Data_BCP_Transformed
;


















SELECT TOP 10 * FROM dbo.Dummy_Data_BCP_05_Staging WHERE AWP_Unit_Price IS NOT NULL;